#!/usr/bin/env node

const path = require('node:path')
const fs = require('node:fs')

const source = fs.readFileSync(path.join(__dirname, 'src', 'index.js'))
  .toString()

const header = '// AUTOGENERATED, edit src/index.js instead\n\n'

const output = header + source
  .replace(/EQ_BEGIN\('(\w+)'\)/g, (_, str) => {
    return str.split('')
      .map((ch, i) => `w[${i}] === '${ch}'`)
      .join(' && ')
  })
  .replace(/EQ_END\((\d+)\s*,\s*'(\w+)'\)/g, (_, offset, str) => {
    offset = Number(offset)
    return str.split('').reverse()
      .map((ch, i) => `w[l - ${i + 1 + offset}] === '${ch}'`)
      .join(' && ')
  })
  .replace(/'(\w)'/g, (_, char) => char.charCodeAt(0))
  .replace(/"(')"/g, (_, char) => char.charCodeAt(0))

fs.writeFileSync(path.join(__dirname, 'dist', 'index.js'), output)
